tests/gles1: fix compilation with newer mesa
Recent mesa update broke GLES1 tests compilation, seems mesa's GLES includes
got some cleanup and 'GLchar' isn't provided by default anymore, glext.h
should be included explicitly. The offending type is defined in unused
function prototype, let's remove it to fix the issue and some others for
cleanup.

../tests/gles1/common.h:78:44: error: unknown type name 'GLchar'
 GLuint glsl_shader_load(GLenum type, const GLchar *lines[], size_t count);